---
title: "Importing and exporting data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Importing and exporting data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(CiteSource)
library(dplyr)
```

# Import with a metadata tibble/dataframe

If you want to provide the metadata in a more readable format, you can use a dataframe. This could be imported, generated based on the file names, or created interactively using the tibble::tribble() format as in the example below.

```{r}

file_path <- "../vignettes/working_example_data/"

metadata_tbl <- tibble::tribble(
  ~files,           ~cite_sources, ~cite_labels, 
   "AGRIS.ris",      "AGRIS",       "search",    
   "CAB.ris",        "CAB",         "search",    
   "EconLit.ris",    "EconLit",     "search",    
   "Final.ris",      NA,          "Final",     
   "GreenFile.ris",  "GreenFile",   "search",    
   "McK.ris",        "McK",         "search",    
   "RM.ris",         "RM",          "search",    
   "TiAb.ris",       NA,          "Screened",  
   "WoS_early.ris",  "WoS",         "search",    
   "WoS_later.ris",  "WoS",         "search"
) %>% 
dplyr::mutate(files = paste0(file_path, files))

citations <- read_citations(metadata = metadata_tbl)

```

