---
title: "troubleshooting"

author: ""

date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Source Analysis Across Screening Phases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 10,
  fig.height = 10,
  warning = FALSE
)
```
## About this vignette

This vignette is strictly for internal troubleshooting

```{r, results = FALSE, message=FALSE}
#Install the remotes packages to enable installation from GitHub
#install.packages("remotes")
#library(remotes)

#Install CiteSource
#remotes::install_github("ESHackathon/CiteSource")

#Load the necessary libraries
library(CiteSource)
library(dplyr)
```


```{r}
#Import citation files from a folder
citation_files <- list.files(path = file.path("../vignettes/troubleshooting"), pattern = "\\.ris", full.names = TRUE)

#Print citation_files to double check the order in which R imported our files.
citation_files
```

```{r}
# Import citation files from folder
citation_files <- list.files(path = "working_example_data", pattern = "\\.ris", full.names = TRUE)

# Print list of citation files to console
citation_files

# Set the path to the directory containing the citation files
file_path <- "../vignettes/troubleshooting/"

metadata_tbl <- tibble::tribble(
  ~files,           ~cite_sources, ~cite_labels, 
   "ProcessedDIM.ris",   "DIM",       "processed",    
   "ProcessedLENS.ris",  "LENS",      "processed",    
   "RAWDIM.ris",         "DIM",       "raw",    
   "RAWLENS.ris",        "LENS",      "raw",     

) %>% 

dplyr::mutate(files = paste0(file_path, files))
citations <- read_citations(metadata = metadata_tbl)
```




```{r}
dedup_results <- dedup_citations(citations, merge_citations = TRUE)

unique_citations <- dedup_results$unique

# Count number of unique and non-unique citations from different sources and labels
n_unique <- count_unique(unique_citations)

# Create dataframe indicating occurrence of records across sources
source_comparison <- compare_sources(unique_citations, comp_type = "sources")
```



```{r}
my_heatmap <- plot_source_overlap_heatmap(source_comparison)

my_heatmap
```


```{r}
my_heatmap_percent <- plot_source_overlap_heatmap(source_comparison, plot_type = "percentages")

my_heatmap_percent
```

### Plot overlap as an upset plot
```{r}
my_upset_plot <- plot_source_overlap_upset(source_comparison, decreasing = c(TRUE, TRUE))

my_upset_plot
```


```{r}
my_contributions <- plot_contributions(n_unique,
  center = TRUE,
  bar_order = c("search", "Screened", "Final")
)

my_contributions
```



```{r}
citation_summary_table(unique_citations, screening_label = c("Screened", "Final"))

```


```{r}
unique_citations %>%
  dplyr::filter(stringr::str_detect(cite_label, "Final")) %>%
  record_level_table(return = "DT")
```
  


```{r}
#export_csv(unique_citations, filename = "citesource_working_example.csv", separate = "cite_source")
```


```{r}
#export_ris(unique_citations, filename = "citesource_working_example.ris", source_field = "DB", label_field = "C5")
```



```{r}
#export_bib(unique_citations, filename = "citesource_working_example.bib", include = c("sources", "labels", "strings"))
```


```{r}
#citesource_working_example <-reimport_csv("citesource_working_example.csv")

#citesource_working_example <-reimport_ris("citesource_working_example.ris")

```
