on:
  release:
    types: [released]
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  push:
    branches:
      - main
      - master

name: Deploy

jobs:
  deploy-latest:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.0'

      - name: Install Dependencies
        run: |
          R -e "install.packages(c('shiny', 'rsconnect'))"

       - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='drmatt', token=${{secrets.TOKEN}}, secret=${{secrets.SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'CiteSource_latest', appDir = './inst/shiny-app/CiteSource')" 
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

  deploy-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.release.tag_name != '*test*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.0'

      - name: Install Dependencies
        run: |
          R -e "install.packages(c('shiny', 'rsconnect'))"

      - name: Deploy Shiny App
        uses: rsconnect/shinyapps-deploy@v1
        env:
          RS_ACCOUNT_NAME: "estech"
          RS_APP_NAME: "CiteSource"
        with:
          app_dir: "./inst/shiny-app/CiteSource"
          environment: "release"
          secrets: |
            RS_ACCOUNT_TOKEN=${{ secrets.TOKEN }}
            RS_ACCOUNT_SECRET=${{ secrets.SECRET }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
