on:
  release:
    types: [released]
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]
  push:
    branches:
      - main
      - master

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'

    - name: Install Dependencies
      run: |
        R -e "install.packages(c('shiny', 'rsconnect'))"

    - name: Deploy Shiny App
      if: |
        github.event_name == 'push' || (github.event_name == 'release' && contains(github.event.release.tag_name, 'test'))
      env:
        RS_ACCOUNT_NAME: "drmatt"
        RS_APP_NAME: "CiteSource_test"
      run: R -e "rsconnect::deployApp(appDir = './inst/shiny-app/CiteSource', appName = Sys.getenv('RS_APP_NAME'), account = Sys.getenv('RS_ACCOUNT_NAME'), launch.browser = FALSE)"

    - name: Deploy Release Shiny App
      if: |
        github.event_name == 'release' && !contains(github.event.release.tag_name, 'test')
      env:
        RS_ACCOUNT_NAME: "estech"
        RS_APP_NAME: "CiteSource"
      run: R -e "rsconnect::deployApp(appDir = './inst/shiny-app/CiteSource', appName = Sys.getenv('RS_APP_NAME'), account = Sys.getenv('RS_ACCOUNT_NAME'), launch.browser = FALSE)"
      
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    secrets:
      RS_ACCOUNT_TOKEN: ${{ secrets.TOKEN }}
      RS_ACCOUNT_SECRET: ${{ secrets.SECRET }}

