on:
  release:
    types: [released]
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: Deploy

jobs:
  deploy-latest:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rsconnect
            any::shiny
            github::ESHackathon/CiteSource
      - name: Install dependencies and deploy
        run: |
          R -e "
            rsconnect::setAccountInfo(name='${{secrets.SHINY_LUKAS_ACCOUNT}}', token='${{secrets.SHINY_LUKAS_TOKEN}}', secret='${{secrets.SHINY_LUKAS_SECRET}}'); 
            rsconnect::deployApp(appName = 'CiteSource_latest', appDir = './inst/shiny-app/CiteSource')"

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

  deploy-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.release.tag_name != '*test*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rsconnect
            any::shiny
            github::ESHackathon/CiteSource
      - name: Install dependencies and deploy
        run: |
          R -e "
            rsconnect::setAccountInfo(name='${{secrets.SHINY_LUKAS_ACCOUNT}}', token='${{secrets.SHINY_LUKAS_TOKEN}}', secret='${{secrets.SHINY_LUKAS_SECRET}}'); 
            rsconnect::deployApp(appName = 'CiteSource_latest', appDir = './inst/shiny-app/CiteSource')"

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

