# R CMD check using r-lib/actions (Posit Public Package Manager binaries).
# See https://github.com/r-lib/actions/tree/v2/examples#standard-ci-workflow

name: R-CMD-Check

on:
  workflow_run:
    workflows: ["document-and-deploy"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
