on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  document-and-dispatch:
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'release'
      - name: Delete-Namespace
        run: Rscript -e 'file.remove("NAMESPACE")'          
      - uses: r-lib/actions/setup-pandoc@v2
      - name: system dependencies
        run: sudo apt-get install libcurl4-openssl-dev libnode-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::roxygen2, any::devtools
          needs: check
      - name: Update date
        run: Rscript -e 'descr <- readLines("DESCRIPTION")' -e 'descr <- stringr::str_replace(descr, "^Date.*$", paste("Date:", Sys.Date()))' -e 'writeLines(descr, "DESCRIPTION")' 
      - name: Document
        run: Rscript -e 'roxygen2::roxygenise(); devtools::build_manual()'
        
      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f man/\* NAMESPACE
          git commit -m 'Documentation' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
        
      - uses: r-lib/actions/check-r-package@v2
