# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: R-CMD-Check

on:
  workflow_run:
    workflows: ["document-and-deploy"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:    

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  R-CMD-check:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci-setup@master

      - name: Bootstrap
        run: ./run.sh bootstrap

      - name: Install rcmdcheck
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          R -e "
            install.packages(c('rcmdcheck', 'devtools'));
            devtools::install_local()
          "

      - uses: r-lib/actions/check-r-package@v2
